name: Helm Render and Install on KinD

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  helm-kind:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up KinD cluster
        uses: helm/kind-action@v1

      - name: Set up Helm
        uses: azure/setup-helm@v4

      - name: Render Helm template
        run: helm template trident ./ > rendered.yaml

      - name: Install Helm chart
        run: kubectl apply -f rendered.yaml

      - name: Get all resources
        run: kubectl get all -A