name: Release Helm Charts
on:
  push:
    tags:
      - v*
jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      - name: Generate a changelog
        uses: orhun/git-cliff-action@v4
        id: git-cliff
        with:
          config: cliff.toml
          args: -v --latest --strip header
        env:
          GITHUB_REPO: ${{ github.repository }}
          OUTPUT: CHANGES.md
      - name: Generate the full changelog
        uses: orhun/git-cliff-action@v4
        with:
          config: cliff.toml
        env:
          OUTPUT: CHANGELOG.md
          GITHUB_REPO: ${{ github.repository }}
      - name: Commit
        run: |
          git checkout main
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          set +e
          git add CHANGELOG.md
          git commit -m "chore: Update changelog"
          git push https://${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git main
      - name: Prepare version
        run: |
          export TAG=$(echo ${{ github.ref }} | cut -d '/' -f 3 - )
          export VERSION=${TAG#v} # tag without leading v
          echo TAG=${TAG} >> $GITHUB_ENV
          echo "TAG: ${TAG}"
          echo VERSION=${VERSION} >> $GITHUB_ENV
          echo "VERSION: ${VERSION}"
      - name: Run chart-releaser
        uses: stefanprodan/helm-gh-pages@v1.7.0
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          app_version: "${{env.TAG}}"
          chart_version: "${{env.VERSION}}"
          charts_dir: helm